### ISSUE TITLE
Edge Selenium tests are crashing on Ubuntu

### ISSUE THREAD

**Issue by bwalderman** [MicrosoftEdge/EdgeWebDriver#10]
First reported on twitter: https://twitter.com/diegofmolina/status/1509254663215927306

Link to test logs: https://github.com/SeleniumHQ/selenium/runs/5746311483?check_suite_focus=true#step:10:162

**Comment by diemol** [comment]
@bwalderman thanks for trying to reproduce. I was using bazel to run our tests and it seems we are doing something that causes the issue, I ran a simple test with maven and it all works well under Ubuntu. 

Please feel free to close this issue.

**Comment by bwalderman** [comment]
Thanks for confirming. I'll go ahead and close this. Feel free to open another issue in this repo if you encounter any Edge-specific bugs.
