### ISSUE TITLE
Window.FullScreen()  should behave the same way as F11

### ISSUE THREAD

**Issue by rpertusio** [MicrosoftEdge/EdgeWebDriver#107]
**The request:**
**Please make Window.FullScreen() perform the same action as "F11" (or, alternately, allow access to press F11)**

**Why?**
**EdgeDriver.Manage().Window.FullScreen() is rudimentary.**
- It offers no UI (other than an overlay text) to get out of FullScreen mode
- It goes back to Windowed mode if any action is performed (such as Navigate.GoToURL() will make it come out of Fullscreen mode)

vs.
**The F11 key on the keyboard to go 'Full Screen' is elegant.**
- Offers a rich UI (mouse hover to top of window allows tab/URL selection, Minimize/Restore/Close buttons)
- Stays in fullscreen mode if action is performed (like Navigate.GoToURL()

Thanks!

**Comment by jbakeri4** [comment]
In the interim, why not just programmatically send the key combination to the app?

**Comment by rpertusio** [comment]
> In the interim, why not just programmatically send the key combination to the app?

Unfortunately, unless I missed something, SendKeys won't send F11 or other function keys to Edge. It will send keys like Tab OK. It doesn't work with Actions or SendKeys. Same for Chrome.

**Comment by bwalderman** [comment]
The Fullscreen command is working as designed here. The WebDriver spec requires the Fullscreen window command to simulate using `Element.fullscreen` on the current document: https://w3c.github.io/webdriver/#fullscreen-window

You can exit fullscreen by calling the window Maximize command.
