### ISSUE TITLE
"DevToolsActivePort file doesn't exist" 116.0.1938.69

### ISSUE THREAD

**Issue by MacAarburger** [MicrosoftEdge/EdgeWebDriver#109]
hi, we can't seem to fix this exception:

```
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: DevToolsActivePort file doesn't exist 
Host info: host: 'K62562', ip: '10.171.85.61'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [--remote-allow-origins=*, --no-sandbox, --disable-dev-shm-usage, --remote-debugging-port=0, --headless], binary: C:\Program Files (x86)\Micr..., extensions: []}}]}]
```

none of the S/O suggested solutions worked
--no-sandbox
--disable-dev-shm-usage
--remote-debugging-port=0
--headless

we're using:
- selenium 4.11.0
- edge 116.0.1938.62
- edge webdriver 116.0.1938.62 (via bongarcia WebDriverManager or selenium EdgeDriverService)
- java 17 (17.0.5 on my machine, 17.0.8 on others)

i saw on other issues to execute this command:
```
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --allow-pre-commit-input --disable-background-networking --disable-backgrounding-occluded-windows --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-service-autorun --password-store=basic --remote-debugging-port=0 --start-maximized --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Users\ue62541\AppData\Local\Temp\scoped_dir21720_1765573058" data:,
```
which ran, opened edge, but did not create a DevToolsActivePort file in the temp folder.

here's my current code:
```
            System.setProperty("webdriver.edge.verboseLogging", "true");

            // WebDriverManager.edgedriver().setup();
            // final EdgeOptions edgeOptions = new EdgeOptions();
            // edgeOptions.addArguments("--no-sandbox");
            // edgeOptions.addArguments("--disable-dev-shm-usage");
            // edgeOptions.addArguments("--remote-debugging-port=0");
            // return new EdgeDriver(edgeOptions.merge(capabilities));

            EdgeDriverService service = new EdgeDriverService.Builder()
                    .withLoglevel(ChromiumDriverLogLevel.DEBUG)
                    .withLogOutput(System.out)
                    .withReadableTimestamp(true)
                    // .usingPort(32123)
                    .build();
            final EdgeOptions edgeOptions = new EdgeOptions();
            edgeOptions.addArguments("--no-sandbox"); // Bypass OS security model
            edgeOptions.addArguments("--disable-dev-shm-usage"); // overcome limited resource problems
            edgeOptions.addArguments("--remote-debugging-port=0");
            // edgeOptions.addArguments("--remote-debugging-port=32123");
            edgeOptions.addArguments("--headless"); // no browser window
            return new EdgeDriver(service, edgeOptions);
```

enabling the first commented block uses the old bongarcia WebDriverManager with the same result.
enabling the ports in the lower portions leads to
"Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: chrome not reachable"

here's the log:
```
Starting Microsoft Edge WebDriver 116.0.1938.62 (493f2197e519d4dde5309fdf4abf4f719089372d) on port 6878
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
[1693388667.880][INFO]: [8bf1f61dd2328febc9c10702cf0de3e7] COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "browserName": "MicrosoftEdge",
         "ms:edgeOptions": {
            "args": [ "--remote-allow-origins=*", "--no-sandbox", "--headless", "--disable-dev-shm-usage", "--remote-debugging-port=0" ],
            "binary": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
            "extensions": [  ]
         }
      } ]
   }
}
[1693388667.881][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1693388667.883][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1693388667.889][INFO]: Launching Microsoft Edge: "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --allow-pre-commit-input --disable-background-networking --disable-backgrounding-occluded-windows --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-logging --headless --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-allow-origins=* --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Users\ue62541\AppData\Local\Temp\scoped_dir13572_127664295" data:,
[1693388727.955][INFO]: Failed to connect to msedge. Attempting to kill it.
[1693388728.011][INFO]: [8bf1f61dd2328febc9c10702cf0de3e7] RESPONSE InitSession ERROR unknown error: DevToolsActivePort file doesn't exist
[1693388728.011][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1693388728.012][DEBUG]: Log type 'browser' lost 0 entries on destruction
```

any help?

**Comment by Ramuvelpula96** [comment]
I'm also facing this while deploying applications on Tomcat -for Edge 

this is my code

System.setProperty("webdriver.chrome.driver", chromeDriverPath);
		System.setProperty("webdriver.edge.driver", edgeDriverPath);
		
		// Added this code to make it work for latest version of chrome and pass this
		// as param to the ChromeDriver.
		
		ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--remote-allow-origins=*");
         
         
        EdgeOptions edgeOptions = new EdgeOptions();
        edgeOptions.addArguments("--remote-allow-origins=*");
        
      
       
		if (gridUrl.isBlank()) {
			switch (browser.toUpperCase()) {
			 
			case "CHROME":
 				webDriver = new ChromeDriver(chromeOptions);
				break;
			case "EDGE":
 				webDriver = new EdgeDriver(edgeOptions);
				break;
				
			default:
 				webDriver = new ChromeDriver(chromeOptions);

			}
		} else {
			switch (browser.toUpperCase()) {
			case "CHROME":
				chromeOptions.setPageLoadStrategy(PageLoadStrategy.NORMAL);
				try {
 					webDriver = new RemoteWebDriver(new URL(gridUrl), chromeOptions);
				} catch (MalformedURLException e) {
					e.printStackTrace();
				}
				break;
			case "EDGE":	

				edgeOptions.setPageLoadStrategy(PageLoadStrategy.NORMAL);
				try {
 					webDriver = new RemoteWebDriver(new URL(gridUrl), edgeOptions);
				} catch (MalformedURLException e) {
					e.printStackTrace();
				}
				break;
			default:                                               
 				webDriver = new ChromeDriver(chromeOptions);
			}
		}
		webDriver.manage().deleteAllCookies();
		webDriver.manage().window().maximize();
		webDriver.get(environmenturl);

	}

**Comment by MacAarburger** [comment]
today it looks a little different.
i remembered that i did not include the .log file, just the console output.
in trying to attach the log, i cleaned out the temp folder (those files and folders that let me delete them) to see the scoped_dir* folder better.

now i noticed that a single test run creates 2 folders
![image](https://github.com/MicrosoftEdge/EdgeWebDriver/assets/24226914/4971fc74-bab2-4cf4-8611-aba1abd25dce)
and after the exception is thrown, both folders are automatically deleted.

**Comment by Ramuvelpula96** [comment]
Are You Running the test cases on a Virtual machine or On a Local? 
For Me. when  I'm running test cases using the Tomcat server it works fine for both browsers
But while deploying the application on Tomcat only I'm getting this issue.

**Comment by MacAarburger** [comment]
we only have it local and on grid.
on openshift we start a RemoteWebDriver for browserstack which works.
`return new RemoteWebDriver(new URL(SELENIUM_SERVER_URL), capabilities);`

**Comment by MacAarburger** [comment]
ok, new selenium version 4.12.1, here are the logs:
```
[09-05-2023 15:00:33.105][INFO]: Starting Microsoft Edge WebDriver 116.0.1938.69 (62ef76ea75c44d490d3c9ecfe141c16f8d79df48) on port 32123
[09-05-2023 15:00:33.106][INFO]: Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.
[09-05-2023 15:00:34.289][INFO]: [3396717d0bd6f00ceff873c3262b29c4] COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "browserName": "MicrosoftEdge",
         "ms:edgeOptions": {
            "args": [ "--remote-allow-origins=*", "--no-sandbox", "--headless", "--disable-dev-shm-usage", "--remote-debugging-port=0" ],
            "binary": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
            "extensions": [  ]
         }
      } ]
   }
}
[09-05-2023 15:00:34.291][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[09-05-2023 15:00:34.293][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[09-05-2023 15:00:34.301][INFO]: Launching Microsoft Edge: "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --allow-pre-commit-input --disable-background-networking --disable-backgrounding-occluded-windows --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-logging --headless --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-allow-origins=* --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Users\ue62541\AppData\Local\Temp\scoped_dir16020_1359599471" data:,
[09-05-2023 15:01:34.384][INFO]: Failed to connect to msedge. Attempting to kill it.
[09-05-2023 15:01:34.492][INFO]: [3396717d0bd6f00ceff873c3262b29c4] RESPONSE InitSession ERROR unknown error: DevToolsActivePort file doesn't exist
[09-05-2023 15:01:34.492][DEBUG]: Log type 'driver' lost 0 entries on destruction
[09-05-2023 15:01:34.492][DEBUG]: Log type 'browser' lost 0 entries on destruction

```
now all logs go to the logfile, no more messages in sysout, other than the exception
```
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: DevToolsActivePort file doesn't exist 
Host info: host: 'K62562', ip: '10.171.85.61'
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [--remote-allow-origins=*, --no-sandbox, --headless, --disable-dev-shm-usage, --remote-debugging-port=0], binary: C:\Program Files (x86)\Micr..., extensions: []}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:163)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:60)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:56)
	at ch.sbb.zvs.testhub.test.extension.selenium.WebDriverFactory.getLocalDriver(WebDriverFactory.java:144)
	at ch.sbb.zvs.testhub.test.extension.selenium.WebDriverFactory.createDriver(WebDriverFactory.java:55)
	at ch.sbb.zvs.testhub.test.extension.selenium.SeleniumSupport.beforeEach(SeleniumSupport.java:74)
```

**Comment by rrodriguez25** [comment]
Also having same issue when running on Jenkins
It works fine if I try running locally

Error log
Error Message:
12:15:37    System.Collections.Generic.KeyNotFoundException : The given key 'WebDriver' was not present in the dictionary.
12:15:37 TearDown : System.Collections.Generic.KeyNotFoundException : The given key 'WebDriver' was not present in the dictionary.
12:15:37   Stack Trace:
12:15:37      at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
12:15:37    at TechTalk.SpecFlow.SpecFlowContext.Get[T](String key)
12:15:37    at Gen5UIProject.Hook.ExtentReport.GetScreenshot(String name) in C:\soft\Gen5Test\Gen5Project\ExtentReport\ExtentReport.cs:line 91
12:15:37    at Gen5UIProject.Hook.ExtentReport.Create_ReportingSteps() in C:\soft\Gen5Test\Gen5Project\ExtentReport\ExtentReport.cs:line 74
12:15:37    at Gen5UIProject.Hook.TestInitialize.InsertReportingSteps() in C:\soft\Gen5Test\Gen5Project\Hook\TestInitialize.cs:line 49
12:15:37    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
12:15:37    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
12:15:37    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnStepEnd()
12:15:37    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
12:15:37    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.Step(StepDefinitionKeyword stepDefinitionKeyword, String keyword, String text, String multilineTextArg, Table tableArg)
12:15:37    at TechTalk.SpecFlow.TestRunner.Given(String text, String multilineTextArg, Table tableArg, String keyword)
12:15:37    at Gen5UIProject.Features.ESI_AA_LoginFeature.TestLoginFunctionalityOfESIWeb(String browsers, String[] exampleTags) in C:\soft\Gen5Test\Gen5Project\Features\ESI_AA_Login.feature:line 7
12:15:37 --TearDown
12:15:37    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
12:15:37    at TechTalk.SpecFlow.SpecFlowContext.Get[T](String key)
12:15:37    at Gen5UIProject.Hook.TestInitialize.KillDriver() in C:\soft\Gen5Test\Gen5Project\Hook\TestInitialize.cs:line 69
12:15:37    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
12:15:37    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
12:15:37    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioEnd()
12:15:37    at TechTalk.SpecFlow.TestRunner.OnScenarioEnd()
12:15:37    at Gen5UIProject.Features.ESI_AA_LoginFeature.TestTearDown()
12:15:37   Standard Output Messages:
12:15:37  Starting Test login functionality of ESI Web
12:15:37  Given I navigate to ESI Web on edge
12:15:37  -> error: unknown error: Microsoft Edge failed to start: crashed.
12:15:37    **(unknown error: DevToolsActivePort file doesn't exist)
12:15:37    (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)**

**Comment by MacAarburger** [comment]
we found out, that this may have been disabled by a security change in our organization.
normally you could check these settings in edge by opening a new tab and navigating to  edge://flags
but here we also get a security block saying "Diese Seite wurde von Ihrem Administrator blockiert" which translates to 'this page was blocked by your administrator'.
we are currently looking into generating an exception for our dev machines.
i will report back if this resolves our issue.

i hope this can help others with the same issue

**Comment by MacAarburger** [comment]
SOLUTION:
the security policy change was the culprid.

after 
1) gaining local admin rights
2) setting this flag in the registry: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\
RemoteDebuggingAllowed = 1 (hex)
3) opening edge browser, navigating to edge://policy, and refreshing the policy (as a result on the lower half remote debugging allowed will be shown as TRUE)
4) now debugging is possible as before.
