### ISSUE TITLE
 Not able to read url to parallel instances in edge browser for IE mode using selenium

### ISSUE THREAD

**Issue by Akshatha-chowta** [MicrosoftEdge/EdgeWebDriver#11]
Edge(IE mode), parallel instance of edge in IE mode does not open/load the URL. It load's the URL only in one instance, for rest of the instances URL does not load(struck on localhost #### page). Also, no error is thrown by the selenium.
In console it is not showing any error logs , it is showing all expected execution steps.
Operating system: windows 10, selenium version : Selenium 4.1.2, browser version: edge 99.0.1150.55, browser driver: IEDriverServer 4.0.0
Please find below repository for above illustrated issue.
https://github.com/YogeshBathri/EdgeIEMode.git
You can use testng.xml suite to run .
Also make sure in edge browser setting,
     1.Internet explorer mode button should be : ON
      2.Allow sites to reloaded in internet Explorer mode should be :ALLOW
I have raised this issue in seleniumhq as well: https://github.com/SeleniumHQ/selenium/issues/10495

**Comment by bwalderman** [comment]
Closing this issue since the above PR has been merged and is available in the latest IEDriver.
