### ISSUE TITLE
Edge has very slow(odd) loading speed compare to chrome

### ISSUE THREAD

**Issue by ryankert01** [MicrosoftEdge/EdgeWebDriver#118]
Many times it will legged, and takes nearly 10 second to load a website. But when I minimize it and suddenly open it, it works as usual. Also, I cannot use control+c to copy, can only use right click, or it will legged like above.

using a Windows11 operating system, intel i5-1300k, RTX3060Ti, 32gb memory.

**Comment by ryankert01** [comment]
btw, chrome don't have those problems, so I'm pretty sure it's a software problem.

**Comment by jbakeri4** [comment]
What version of Edge is installed? 
What channel of Edge is installed?
How much RAM does Task Manager report Edge is using?

**Comment by ryankert01** [comment]
Version 117.0.2045.55 (Official build) (64-bit) look like stable version
stable
it use approx 1gb memory

**Comment by ryankert01** [comment]
I just find out this problem is caused by Microsoft Remote Desktop. 
Can be solved by restart.
