### ISSUE TITLE
How to determine the correct Microsoft Edge WebDriver version for a given Edge browser version

### ISSUE THREAD

**Issue by devfemibadmus** [MicrosoftEdge/EdgeWebDriver#158]
I'm trying to match the correct version of the Microsoft Edge WebDriver with the installed version of the Microsoft Edge browser on my Debian system. The version numbers between the browser and the driver don't always align, making it confusing to determine which driver version to use. Sometimes the WebDriver has a version number that the browser doesn't have, or vice versa.

I tried installing a WebDriver with the same version number as the browser, but this doesn't seem to be the best solution. For instance, I currently have version `123.0.2420.53` of both the browser and the driver, and it works fine. However, I can't rely on this approach every time as the versions don't always match.

Here's my current process for installation:

1.  Visit [https://msedgedriver.azureedge.net/](https://msedgedriver.azureedge.net/) to see the list of available WebDriver versions.
2.  Run `sudo apt list -a microsoft-edge-stable` to find the latest browser release.
3.  Look for an exact version match, if available.

However, this method is cumbersome and unreliable, especially when the latest WebDriver and browser versions do not match, causing version errors. How can I accurately determine the correct WebDriver version for my installed Edge browser version? Is there a more systematic way to handle this?

Any guidance or resources would be appreciated!

**Comment by ghostwords** [comment]
This script has been working for us: https://github.com/EFForg/privacybadger/blob/af7092e70fbd0c142a4954ae4e8200b687a4b42f/scripts/setup_travis.sh#L6-L24

**Comment by devfemibadmus** [comment]
> This script has been working for us: https://github.com/EFForg/privacybadger/blob/af7092e70fbd0c142a4954ae4e8200b687a4b42f/scripts/setup_travis.sh#L6-L24

Oh thanks similar to my method

**Comment by bonigarcia** [comment]
[Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) does this job. It can be used as CLI tool, if you need to download msedgedriver.
