### ISSUE TITLE
No support for Apple silicon?

### ISSUE THREAD

**Issue by dannybloe** [MicrosoftEdge/EdgeWebDriver#17]
Howdee,

On MacOs I am running the ARM version of Edge without problems. The webdriver however is extremely slow as it runs under Rosetta. Is there an Arm version of the driver? I tried 101.0.1210.32.

Kind regards, 
Danny

**Comment by bwalderman** [comment]
Thank you for the feedback. We don't currently release an ARM version of the driver for Mac. I've added this request to our internal backlog.

**Comment by dannybloe** [comment]
Yes please because for now running tests on Edge with this webdriver is just too slow. Nearly half as fast as the Chrome wedriver which runs without emulation on Apple silicon. Fortunately there is not much difference between Edge and Chrome so I'll just skip Edge for now in my tests until this is fixed.

**Comment by bwalderman** [comment]
@dannybloe, I have some good news. We've enabled Mac ARM builds of Edge WebDriver for Edge 105. Links should be published to https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ as soon as Edge 105 Stable is released.

**Comment by bwalderman** [comment]
Mac ARM builds are now available for all channels.  You can download the current stable release 105.0.1343.50 at https://msedgedriver.azureedge.net/105.0.1343.50/edgedriver_mac64_m1.zip
