### ISSUE TITLE
EdgeWebdriver download

### ISSUE THREAD

**Issue by Demilson-Lino** [MicrosoftEdge/EdgeWebDriver#176]
Ao acessar o site para baixar o webdriver atual do EDGE, está ocorrendo o seguinte erro : "Opa, ocorreu um erro.
Cannot read properties of undefined (reading 'default')"

**Comment by brubcruz** [comment]
Mesmo problema.
Não sei desde que horas esta isso.
E pelo jeito não tem outra fonte de download.

**Comment by brubcruz** [comment]
Demilson.
O jeito que eu resolvi foi baixar diretamente.
Usei esse link:
https://msedgedriver.azureedge.net/131.0.2903.51/edgedriver_win64.zip

Veja se te ajuda.
Boa sorte.

**Comment by Demilson-Lino** [comment]
> Demilson. O jeito que eu resolvo foi baixar diretamente. Use esse link: https://msedgedriver.azureedge.net/131.0.2903.51/edgedriver_win64.zip
> 
> Veja se te ajuda. Boa sorte.

**Comment by Demilson-Lino** [comment]
Obrigado pela dica @brubcruz, consegui atualizar a versão para a mais recente "131.0.2903.51".
