### ISSUE TITLE
Session timeout exception while launching Edge in IE mode

### ISSUE THREAD

**Issue by SubhenduShekhar** [MicrosoftEdge/EdgeWebDriver#20]
See, https://github.com/SeleniumHQ/selenium/issues/10633

## Steps to re-produce:
Language: C#
1. Download Selenium.Webdriver v4.1.1
2. Download 32-Bit IEDriverServer.exe v4.0.0 or higher and put it in path(say C:/Drivers/IEDriverServer.exe)
3. Use below script:

```using OpenQA.Selenium.IE;

namespace SeleniumTest
{
    class Program
    {
        static void Main(string[] args) {

            var driver = new InternetExplorerDriver(@"C:\Driver", new InternetExplorerOptions
            {
                AttachToEdgeChrome = true,
                EdgeExecutablePath = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
                IgnoreZoomLevel = true
            });
        }
    }
}
```

After launch of Edge, the control is never sent back to scripts.

## Output
OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://localhost:53359/session timed out after 60 seconds.'

**Comment by bwalderman** [comment]
I tried the sample script and it runs successfully. From the linked SeleniumHQ issue, it sounds like you've already done the required configuration in https://www.selenium.dev/documentation/ie_driver_server/ so I could use some more information:

- Windows version
- Edge version
- Any other details about the environment (is it a VM, a physical machine?, etc..)

**Comment by SubhenduShekhar** [comment]
Sure,
Here are the details:
OS: Windows 10
Edge version: 101.0.1210.39
Selenium version: 4.0.0 or higher
Its a physical machine.

**Comment by bwalderman** [comment]
Is Internet Explorer enabled as a Windows feature? I believe this is still necessary for IE Mode in Edge.

You can also try using either the 32-bit or 64-bit version of IEDriver https://www.selenium.dev/downloads/ and seeing whether that helps.

**Comment by bwalderman** [comment]
I am going to close this issue since there hasn't been any recent comments. Feel free to reopen if you are able to provide more details.
