### ISSUE TITLE
Bug in either Webdriver 103.*.* or Edge 103.*.* - unexpected command response

### ISSUE THREAD

**Issue by trontronicent** [MicrosoftEdge/EdgeWebDriver#21]
** Issue **
Massive ammount of **"Unknown error: unexpected command response"** as possible outcome to allmost every Webdriveraction. An error i havent seen before on my logs, now dominating my logs. 

** Platforms **
Windows 11 , Release , fully patched
Windows Server 2022 Evaluation Build

** Framework **
Selenium 4.1.1 (.NET / C#) - sorry guys, but can't test something else - C#NET is my domain ;) - but from what I see, and due to my logs, I doubt the framework is related to it - because it didnt change in the time between working condition and this massive number of fails now.

** Webdrivers Affected (Tested) **
103.0.1256.0 x64
103.0.1255.0 x64
103.0.1254.0 x64

** Tested Against Ms Edge Version ** 
103.0.1256.0 (happened before already, but due to the fact that my test environments arent domain joined and im not using Docker or VMs I cannot revert back to another version). 

** Personal Thoughts **
Due to the fact, that this error can and does occur as reaction to both, W3C and DevToolsProtocol communication - which are independent from each other, I suspect its either something happening down on the network level of the webdriver. Doing CDP communication independently from webdriver (manually via websocket from C#) i dont get anything I would interpret as unexpected command response. Unfortunately, the Webdriver (or better the bindings) dont give back the command response which is unexpected, so I could probably see whats driving him mad.
I also think, I can exclude my personal environment as source of evil, as it's independent systems, running on different operating systems, running totally different tests.

If the issue lies outside of your scope, then i apologize, I did my best to check what I can to try to ensure to not waste your time.

** Some Data (basically useless from the informational point of view ** 
{
  
HResult: -2146233088,
  
Message: 'unknown error: unexpected command response
  (Session info: MicrosoftEdge=103.0.1256.0)',
  
Source: 'WebDriver',
  
StackTrace: '   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.WebDriver.ExecuteScript(String script, Object[] args)

{HResult: -2146233088, Message: 'unknown error: unexpected command response
  (Session info: MicrosoftEdge=103.0.1255.0)', Source: 'WebDriver', StackTrace: '   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.FindElements(String mechanism, String value)
   at OpenQA.Selenium.By.<.ctor>b__11_1(ISearchContext context)
   at OpenQA.Selenium.By.FindElements(ISearchContext context)
   at OpenQA.Selenium.WebDriver.FindElements(By by)

**Comment by bwalderman** [comment]
Thank you for reporting this. Do you seen the same errors when testing with Chrome and ChromeDriver 103?

**Comment by trontronicent** [comment]
> Thank you for reporting this. Do you seen the same errors when testing with Chrome and ChromeDriver 103?

Ill test tonight, I switched actually to the Edge/Edgedriver because of such issues over long periods - switched around v90 - and since then I had a good run with Edge/Edgedriver without any such issues - the chromedriver was always problematic ;)

One thing I recon (which I remember from Chrome/Chromedriver) - sudden Socketexceptions - and once this happens, the driver remains in a running state, but times out on all requests and cannot be normally "closed" .  
I'll change my tests to full verbosity tonight and add some runs with Chrome, posting the results.

**Comment by trontronicent** [comment]
This is what i could fetch as close as possible to the source as the 0815 debugger is able to properly handle 

{"value":{"error":"unknown error","message":"unknown error: unexpected command response\n  (Session info: MicrosoftEdge=103.0.1262.0)","stacktrace":"Backtrace:\n\tMicrosoft::Applications::Events::EventProperties::unpack [0x00007FF7C4D87F32+20210]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x00007FF7C4CF6042+286162]\n\tOrdinal0 [0x00007FF7C4779B55+629589]\n\tOrdinal0 [0x00007FF7C4766D4C+552268]\n\tOrdinal0 [0x00007FF7C47661FF+549375]\n\tOrdinal0 [0x00007FF7C47655E9+546281]\n\tOrdinal0 [0x00007FF7C4764CD3+543955]\n\tOrdinal0 [0x00007FF7C4764B40+543552]\n\tOrdinal0 [0x00007FF7C477AF51+634705]\n\tOrdinal0 [0x00007FF7C47E3D30+1064240]\n\tOrdinal0 [0x00007FF7C47D00E3+983267]\n\tOrdinal0 [0x00007FF7C47A6DD9+814553]\n\tOrdinal0 [0x00007FF7C47A8248+819784]\n\tMicrosoft::Applications::Events::EventProperty::EventProperty [0x00007FF7C4BAD8A8+116600]\n\tMicrosoft::Applications::Events::EventProperty::EventProperty [0x00007FF7C4B99C77+35655]\n\tMicrosoft::Applications::Events::EventProperty::EventProperty [0x00007FF7C4B9CE4C+48412]\n\tMicrosoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7C49492D6+29174]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x00007FF7C4CFD02B+314811]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x00007FF7C4D01A84+333844]\n\tOrdinal0 [0x00007FF7C4861ED3+1580755]\n\tMicrosoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF7C4D0B2FE+35470]\n\tBaseThreadInitThunk [0x00007FFCFF6354E0+16]\n\tRtlUserThreadStart [0x00007FFCFFEC485B+43]\n"}}

Due to the StatusCode I assume we can safely say that the error is on the Edge/Drive side, or could i be wrong? 

I know for sure, there was a combination on the 103.* - quite early in the major - where this error wasnt present or at least not that prominently that it would cause any alerts. Question is just,  is it a change on the driver or on Edge thats causing it - will do some tests with the previous versions against the current Edge binary, maybe i can narrow it down further...

**Comment by bwalderman** [comment]
Thank you for the extra details. I was able to reproduce this error and submitted a fix to Chromium here https://chromium-review.googlesource.com/c/chromium/src/+/3658212

I am going to close this issue. The fix will be available in Edge/Edge WebDriver 104+.

**Comment by tcsmohitwangu** [comment]
This issue is seen on Chrome 103 as well.

**Comment by robinguptaprovar** [comment]
@bwalderman  - Thanks for landing in the fix. How can we build a local version of Chromedriver with the changes here ?
https://chromium-review.googlesource.com/c/chromium/src/+/3658212
