### ISSUE TITLE
Edge Driver does not work in Headless mode for SSO

### ISSUE THREAD

**Issue by arshad-sarfarz** [MicrosoftEdge/EdgeWebDriver#28]
I am using Selenium EdgeDriver for Test Automation. Single Sign does not work for a website, when the EdgeDriver is used in Headless mode. But the same functionality works when used in Normal mode. I get the following error in Headless mode.

"BSSO Telemetry: {"result":"Error","error":"bssoNotSupported","type":"TBAuthTelemetry","data":{"BSSO.info":"not-supported"},"traces":["BrowserSSO Initialized","window.navigator.msLaunchUri is not available for _pullBrowserSsoCookie"]

Can you help me with this?

**Comment by bwalderman** [comment]
Hi @arshad-sarfarz. Headless mode in Chrome and Edge is really a separate product embedded in the main browser, which doesn't share the same user data. When running Edge in headless mode, you will need to explicitly sign into the page before testing.
