### ISSUE TITLE
When calling 'CreateCoreWebView2Controller' in Webview2, it takes about 3 seconds, but I want to reduce it to 1 second. I wonder if there is a better way

### ISSUE THREAD

**Issue by jaehojung** [MicrosoftEdge/EdgeWebDriver#33]
Hello, my name is Jaeho.
I wonder how is solves that calling 'CreateCoreWebView2Controller' in Webview2(win32, version 1.0.1072.54), it takes about 3 seconds, but I want to reduce it to 1 second. I wonder if there is a better way.

**Comment by bwalderman** [comment]
Hello. This repo is for questions about test automation with Microsoft Edge WebDriver, not the WebView2 control. Please post your question to https://github.com/MicrosoftEdge/WebView2Feedback instead.
