### ISSUE TITLE
Selenium EdgeDriver debugging mode

### ISSUE THREAD

**Issue by sunzi37** [MicrosoftEdge/EdgeWebDriver#41]
I'm using C#.
I would like to know how to run it in debuggnig mode using Selenium EdgeDriver.

**Comment by bwalderman** [comment]
Hi @sunzi37. I am not sure what is meant by "debugging mode" in this case. Can you help me understand what you are trying to do?

**Comment by bwalderman** [comment]
I'm going to close this issue since no more information was provided. Feel free to reopen if you have any more info.
