### ISSUE TITLE
Edge Browser Closes Immediately

### ISSUE THREAD

**Issue by knana1662** [MicrosoftEdge/EdgeWebDriver#42]
Edge browser closes immediately as soon as the code begins to run .Please help
![Screenshot 2022-07-26 104245](https://user-images.githubusercontent.com/109052744/180976527-335ac327-c80e-41f5-8df2-853e7ec8d9c7.jpg)

**Comment by bwalderman** [comment]
Can you please share the browser version and driver version that you are using?

**Comment by knana1662** [comment]
Microsoft Edge : 103.0.1264.71 (Official build) (64-bit)
Edge Driver Version : 103.0.1264.71 (64-bit)

**Comment by bwalderman** [comment]
Hi @knana1662. I tried your python script on my machine with Edge 103.0.1264.71 and it launched successfully. Which Python and Selenium versions are you using?

**Comment by knana1662** [comment]
The selenium version is v4.3.0 but the problem is that, it always closes as soon as it opens, once it runs  sucessfully.

**Comment by knana1662** [comment]
Is that something normal to happen or it is just a bug or something else?

**Comment by bwalderman** [comment]
Thanks for confirming. Are you able to run successfully with Chrome and ChromeDriver?

**Comment by knana1662** [comment]
Yes please but it's still the same or do I always have to add a sleep timer before I run the code?

**Comment by bwalderman** [comment]
@knana1662 I don't understand. Does the same problem happen when you try to use Chrome instead of Edge? This will help us find out if the problem is with Edge or with Selenium.

**Comment by knana1662** [comment]
Yes it happens to both Chrome and Edge even with the latest drivers installed.

**Comment by bwalderman** [comment]
Thank you. Since the problem isn't Edge-specific, I'm going to close this issue. I recommend asking for help at https://github.com/SeleniumHQ/selenium instead.
