### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by TheProFesserX** [MicrosoftEdge/EdgeWebDriver#44]
I am observing the above mentioned error while running MS Edge WebDriver via Maven command 'mvn test'

**Selenium Java Code:**

EdgeOptions edgeBrowserOptions = new EdgeOptions();
			edgeBrowserOptions.addArguments("start-maximized");
			edgeBrowserOptions.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
			System.setProperty("webdriver.edge.driver", "C:\\Users\\Biswajit\\Documents\\WebDrivers\\msedgedriver.exe");
			driver = new EdgeDriver(edgeBrowserOptions);

**Error Log:**

00:19:59 [INFO] -------------------------------------------------------
00:19:59 [INFO]  T E S T S
00:19:59 [INFO] -------------------------------------------------------
00:19:59 [INFO] Running TestSuite
00:20:01 02 August 2022 00:20:01,613 endToEndFrameWork.BaseDriverAll [TestNG-tests-1] INFO  - onStart method : Listeners - HomePageTest
00:20:02 Starting Microsoft Edge WebDriver 103.0.1264.77 (2b250f2585e4f7418e51e230b93685cdc0ed9db5) on port 50977
00:20:02 To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver
00:20:02 
00:20:02 Only local connections are allowed.
00:20:02 Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.
00:20:02 
00:20:02 Microsoft Edge WebDriver was started successfully.
00:20:05 02 August 2022 00:20:05,013 endToEndFrameWork.BaseDriverAll [TestNG-tests-1] INFO  - New Test Started : Listeners - HomePageValidation
00:20:05 02 August 2022 00:20:05,022 endToEndFrameWork.BaseDriverAll [TestNG-tests-1] INFO  - onFinish method : Listeners - HomePageTest
00:20:06 Aug 02, 2022 12:20:06 AM org.openqa.selenium.os.OsProcess destroy
00:20:06 SEVERE: Unable to kill process Process[pid=904, exitValue=1]
00:20:07 [ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 7.833 s <<< FAILURE! - in TestSuite
00:20:07 [ERROR] endToEndFrameWork.HomePageTest.initializeBrowser  Time elapsed: 5.185 s  <<< FAILURE!
00:20:07 org.openqa.selenium.SessionNotCreatedException: 
00:20:07 Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: exited normally.
00:20:07   (unknown error: DevToolsActivePort file doesn't exist)
00:20:07   (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)
00:20:07 Build info: version: '4.3.0', revision: 'a4995e2c09*'
00:20:07 System info: host: 'THEPROFESSER', ip: '192.168.29.130', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '18.0.1.1'
00:20:07 Driver info: org.openqa.selenium.edge.EdgeDriver
00:20:07 Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: []}}], desiredCapabilities=Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: []}}}]
00:20:07 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
00:20:07 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
00:20:07 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
00:20:07 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
00:20:07 	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
00:20:07 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
00:20:07 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
00:20:07 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:264)
00:20:07 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:179)
00:20:07 	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
00:20:07 	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:54)
00:20:07 	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:46)
00:20:07 	at endToEndFrameWork.BaseDriverAll.initializeDriver(BaseDriverAll.java:32)
00:20:07 	at endToEndFrameWork.HomePageTest.initializeBrowser(HomePageTest.java:14)
00:20:07 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
00:20:07 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
00:20:07 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
00:20:07 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
00:20:07 	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
00:20:07 	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
00:20:07 	at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:643)
00:20:07 	at org.testng.TestRunner.beforeRun(TestRunner.java:632)
00:20:07 	at org.testng.TestRunner.run(TestRunner.java:594)
00:20:07 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
00:20:07 	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
00:20:07 	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
00:20:07 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:20:07 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
00:20:07 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
00:20:07 	at java.base/java.lang.Thread.run(Thread.java:833)
00:20:07 
00:20:08 [INFO] 
00:20:08 [INFO] Results:
00:20:08 [INFO] 
00:20:08 [ERROR] Failures: 
00:20:08 [ERROR]   HomePageTest.initializeBrowser:14->BaseDriverAll.initializeDriver:32 » SessionNotCreated Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: exited normally.
00:20:08   (unknown error: DevToolsActivePort file doesn't exist)
00:20:08   (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)
00:20:08 Build info: version: '4.3.0', revision: 'a4995e2c09*'
00:20:08 System info: host: 'THEPROFESSER', ip: '192.168.29.130', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '18.0.1.1'
00:20:08 Driver info: org.openqa.selenium.edge.EdgeDriver
00:20:08 Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: []}}], desiredCapabilities=Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: []}}}]

**Comment by bwalderman** [comment]
Hi @TheProFesserX , can you please try enabling verbose logging and sharing the output here? Add the following line in Java:

```
System.setProperty("webdriver.edge.verboseLogging", true);
```

**Comment by TheProFesserX** [comment]
Hi @bwalderman . I have enabled Verbose Logging now. Attaching the logs for the same '[Edge WebDriver Logging.log](https://github.com/MicrosoftEdge/EdgeWebDriver/files/9282174/Edge.WebDriver.Logging.log)'

**Selenium-Java** - v4.3.0
**Edge Browser** - v104.0.1293.47 (64-bit)
**Edge WebDriver** - v104.0.1293.47 (win64) https://msedgewebdriverstorage.z22.web.core.windows.net/?prefix=104.0.1293.47/

**_Re-sharing the logs:_**

Starting Microsoft Edge WebDriver 104.0.1293.47 (246533a39fec5a167e7729d997877afea075bd86) on port 61212
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 9.684 s <<< FAILURE! - in TestSuite
[ERROR] endToEndFrameWork.HomePageTest.initializeBrowser  Time elapsed: 6.642 s  <<< FAILURE!
org.openqa.selenium.SessionNotCreatedException:
Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'THEPROFESSER', ip: '192.168.29.130', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '18.0.1.1'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: []}}], desiredCapabilities=Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: []}}}]
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:264)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:179)
        at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
        at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:54)
        at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:46)
        at endToEndFrameWork.BaseDriverAll.initializeDriver(BaseDriverAll.java:35)
        at endToEndFrameWork.HomePageTest.initializeBrowser(HomePageTest.java:14)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
        at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:643)
        at org.testng.TestRunner.beforeRun(TestRunner.java:632)
        at org.testng.TestRunner.run(TestRunner.java:594)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
        at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   HomePageTest.initializeBrowser:14->BaseDriverAll.initializeDriver:35 » SessionNotCreated Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'THEPROFESSER', ip: '192.168.29.130', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '18.0.1.1'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: []}}], desiredCapabilities=Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: []}}}]
[INFO]
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.153 s
[INFO] Finished at: 2022-08-08T19:12:16+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project End-To-EndFrameWork: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Biswajit\Documents\Eclipse\Workspace\End-To-EndFrameWork\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by TheProFesserX** [comment]
**The Selenium code I am currently using:**

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.Duration;
import java.util.Collections;
import java.util.Properties;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.*;
public class BaseDriverAll {
	public WebDriver driver;
	public Properties property;
	public WebDriver initializeDriver() throws FileNotFoundException, IOException {
		property = new Properties();
		FileInputStream fiStream = new FileInputStream(System.getProperty("user.dir") +"\\resources\\driver.properties");
		property.load(fiStream);
		String browserName = property.getProperty("browser");
		if (browserName.equals("Microsoft Edge")) {
			System.setProperty("webdriver.edge.driver", "C:\\Users\\Biswajit\\Documents\\WebDrivers\\msedgedriver.exe");
			System.setProperty("webdriver.edge.logfile", "C:\\Users\\Biswajit\\Documents\\Eclipse\\VerboseLog\\Edge WebDriver Logging.log");
			System.setProperty("webdriver.edge.verboseLogging", "true");
			EdgeOptions edgeBrowserOptions = new EdgeOptions();
			edgeBrowserOptions.addArguments("start-maximized");
			edgeBrowserOptions.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
			driver = new EdgeDriver(edgeBrowserOptions);			
		}
		driver.manage().deleteAllCookies();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		return driver;
	}
}

**Comment by bwalderman** [comment]
@TheProFesserX it looks like the browser exits on startup and fails to write the DevToolsActivePort file which Edge WebDriver uses to communicate with the browser:

> [ERROR] HomePageTest.initializeBrowser:14->BaseDriverAll.initializeDriver:35 » SessionNotCreated Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: exited normally.
(unknown error: DevToolsActivePort file doesn't exist)
(The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)


What happens if you run the following directly from a command prompt?

```
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --allow-pre-commit-input --disable-background-networking --disable-backgrounding-occluded-windows --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-service-autorun --password-store=basic --remote-debugging-port=0 --start-maximized --test-type=webdriver --use-mock-keychain --user-data-dir="C:\EdgeDriverTemp" data:,
```

If everything is working as expected, Edge should launch, and a C:\EdgeDriverTemp folder should be created. In that folder there should be a text file named DevToolsActivePort. Please try the command above and share your results.

**Comment by bwalderman** [comment]
Closing since there hasn't been any recent activity.
