### ISSUE TITLE
How to run WebDriverIO (TypeScript) with MS Edge in IE Mode

### ISSUE THREAD

**Issue by PavanMudigondaTR** [MicrosoftEdge/EdgeWebDriver#46]
Hi All, Could someone please let me know if its possible to run WebDriverIO(TypeScript) with MS Edge in IE Mode ? If, yes any instructions or guidance is appreciated !

**Comment by bwalderman** [comment]
Closing since this was answered at https://github.com/MicrosoftDocs/edge-developer/issues/2148
