### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found

### ISSUE THREAD

**Issue by VarunKaniyala** [MicrosoftEdge/EdgeWebDriver#48]
I have downloaded latest beta version of Edge Browser and latest Beta version of Edge driver.

**Case:1:**
options = Options()
options.binary_location = r"C:\Programs\Python\Python310\Scripts\msedgedriver.exe"
edgedriver = webdriver.Edge(options=options)

Even after setting up the path in environment variable, while execution I'm getting the below error:

**selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found**

**Case:2:**
By keeping the edge driver inside Scripts folder of Python folder. I tried executing without using the Options as below 
edgedriver = webdriver.Edge(executable_path="msedgedriver.exe")
 
But I'm getting error as below.

E       selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find msedge binary
E       Stacktrace:
E       Backtrace:
E       	Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF6008C31E2+15698]
E       	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6008633F2+1446802]
E       	Ordinal0 [0x00007FF60047CA05+641541]
E       	Ordinal0 [0x00007FF6004A4E67+806503]
E       	Ordinal0 [0x00007FF6004A1790+792464]
E       	Ordinal0 [0x00007FF6004DFFB1+1048497]
E       	Ordinal0 [0x00007FF6004DF498+1045656]
E       	Ordinal0 [0x00007FF6004D8803+1017859]
E       	Ordinal0 [0x00007FF6004AD214+840212]
E       	Ordinal0 [0x00007FF6004AE88F+845967]
E       	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF600723048+135144]
E       	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF60070CEA8+44616]
E       	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF60070FE4C+56812]
E       	Ordinal0 [0x00007FF600576424+1664036]
E       	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF600868A59+1468921]
E       	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF60086C924+1484996]
E       	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF60086CA7D+1485341]
E       	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6008743F6+1516438]
E       	BaseThreadInitThunk [0x00007FFDFE187974+20]
E       	RtlUserThreadStart [0x00007FFDFFFAA2F1+33]

**Comment by bwalderman** [comment]
```
options = Options()
options.binary_location = r"C:\Programs\Python\Python310\Scripts\msedgedriver.exe"
edgedriver = webdriver.Edge(options=options)
```

The `binary_location` property should point to the msedge binary, not the driver. Since you are using Edge Beta, you will need to set this to the msedge location for Edge Beta. This should be `C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe`.

https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=python#choose-specific-browser-binaries

Note: You don't need to provide this if you are using Edge Stable since the driver can locate Edge Stable automatically.

**Comment by bwalderman** [comment]
Closing this issue since there hasn't been any recent activity. Feel free to re-open if the problem still occurs after trying suggested fix.
