### ISSUE TITLE
Edge Browser launch issue

### ISSUE THREAD

**Issue by Prasanna9792** [MicrosoftEdge/EdgeWebDriver#50]
![20221003_145218](https://user-images.githubusercontent.com/114920581/193566386-50351b65-bf7c-438c-b9da-8f19bb5e7f6c.jpg)
![20221003_145158](https://user-images.githubusercontent.com/114920581/193566413-3ba9af98-44de-42b3-8207-7b79520ba036.jpg)

**Comment by bwalderman** [comment]
Can you please share which version of Selenium you are using?

**Comment by Prasanna9792** [comment]
Hi,
Thank you for your response,

I am using latest version of selenium webdriver dll which is downloaded
from nuget package in visual studio.

**Comment by Prasanna9792** [comment]
Hi, can you please help on this issue

**Comment by bwalderman** [comment]
Hi @Prasanna9792 , I need more information to understand what might be causing the issue. Can you try running with verbose logging enabled, and share the full log output? This example shows how to enable verbose logging:

```csharp
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;

namespace EdgeTesting
{
    class Program
    {
        static void Main(string[] args)
        {
            var service = EdgeDriverService.CreateDefaultService();
            service.EnableVerboseLogging = true;

            IWebDriver driver = new EdgeDriver(service);
            driver.Navigate().GoToUrl("https://bing.com");

            Thread.Sleep(3000);
            driver.Quit();

            service.Dispose();
        }
    }
}
```

**Comment by Prasanna9792** [comment]
I tried above still same issue. Is there any settings needed in my browser?

**Comment by Prasanna9792** [comment]
![Uploading 20221014_11
![20221014_111550](https://user-images.githubusercontent.com/114920581/195771803-75892d2e-89c2-40bc-af1f-be949ddbf517.jpg)
1433.jpg…]()

**Comment by bwalderman** [comment]
Hi @Prasanna9792 , when verbose logging is enabled, you should see much more detailed log output in the console window. I don't see any extra logs in your last screenshot. Please try again, rebuild the project if necessary to ensure `EnableVerboseLogging` is set to `true`, and then share the entire verbose log output as a plain text file if possible. Otherwise, I will not be able to debug the problem further.


Sample log when Edge WebDriver is running with `EnableVerboseLogging`. You should see output similar to this. Note the extra JSON command info:

```
Starting Microsoft Edge WebDriver 106.0.1370.47 (4e0bb7311a0aef386b78ea449062b0dc1fb738fe) on port 56597
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
[1666293553.968][INFO]: [48744621c425446888560bd331858ac1] COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "browserName": "MicrosoftEdge",
         "ms:edgeOptions": {
         }
      } ]
   }
}
...
```

**Comment by bwalderman** [comment]
Closing this issue since there hasn't been any follow up. Feel free to reopen if you would like to provide more information.
