### ISSUE TITLE
MS_Edge "EdgeShoppingAssistantEnabled"

### ISSUE THREAD

**Issue by sammeboy635** [MicrosoftEdge/EdgeWebDriver#51]
Hello, a little unclear where I should ask this question but I have a question about a way to disable "EdgeShoppingAssistantEnabled" settings from either a --disable-features=EdgeShoppingAssistantEnabled (doesn't work) or a remote devtools command. Does anyone know where I can get some information about adjusting this setting?

**Comment by bwalderman** [comment]
Hi @sammeboy635, "EdgeShoppingAssistantEnabled" is a group policy, and these can't be set through command line, or automation. The shopping feature can also be enabled/disabled through the user preferences instead, which is equivalent to toggling the shopping feature in `edge://settings`. To set the pref, try the following snippet (assuming C#, but this should work in any language):

```csharp
var options = new EdgeOptions();
options.AddUserProfilePreference("edge_shopping_assistant_enabled", false);
```

**Comment by sammeboy635** [comment]
Thanks for that info @bwalderman. I was hoping for a command line argument or remote devtools command. This is the issue i'm trying to solve (https://github.com/WPO-Foundation/webpagetest/issues/2396).
