### ISSUE TITLE
What happened to Linux builds on the Microsoft Edge WebDriver page?

### ISSUE THREAD

**Issue by ghostwords** [MicrosoftEdge/EdgeWebDriver#52]
One used to be able to find links to Linux builds on the [Microsoft Edge WebDriver page](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/). These links no longer appear to be there.

We were using these links to discover the appropriate Edge WebDriver version:

https://github.com/EFForg/privacybadger/blob/3703edfdaac28ea79aa13cf30c1406beac31c3e6/scripts/setup_travis.sh#L10

This is related to #39 / #40.

AB#41824748

**Comment by bwalderman** [comment]
Thanks. I've added this to our team's internal backlog to investigate.

**Comment by bwalderman** [comment]
Fixed.
