### ISSUE TITLE
Edge Webdriver 107.0.1418.28 not available for windows in official microsoft repo

### ISSUE THREAD

**Issue by THEETB** [MicrosoftEdge/EdgeWebDriver#57]
Hi,

 I have a developed a wrapper which use microsoft edge webdriver to launch RStudio Server Tool. My wrapper pull the webdriver from official microsoft repository (https://msedgewebdriverstorage.z22.web.core.windows.net/?prefix=107.0.1418.28/) if the edge browser get updated to latest version. But the webdriver is not available in microsoft official repository for windows. Any suggestion to fix this issue ?

Thanks

**Comment by GCuser99** [comment]
I ran into similar issue as well. The url https://msedgedriver.azureedge.net/LATEST_RELEASE_107 returns 107.0.1418.28, but that version, as of today, is only available for Mac OS, whereas the previous version for same build, 107.0.1418.26, is only available for Windows. Maybe the api should be operating system aware?

**Comment by bwalderman** [comment]
@THEETB, @GCuser99, Edge sometimes publishes a minor release for specific platforms only. 107.0.1418.28 is a Mac and Linux release. The closest release with a Windows build should be 107.0.1418.26.

URLs such as LATEST_RELEASE_107 are available for legacy reasons, but are generally not reliable for this reason and should be avoided. The best way to ensure your drivers are up to date is to use a solution such as [WebDriverManager](https://bonigarcia.dev/webdrivermanager/).

If you would like to avoid a third-party dependency, or would rather use your own solution for updating the driver, the best approach is to get the exact version number of the installed Edge binary. You can do this on Windows with a single powershell command: `(Get-Item 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe').VersionInfo.FileVersion`

**Comment by THEETB** [comment]
Hi, 

I think the wrapper which using actually looks for OS based webdriver since the webdriver are categorized by the os name. I don't think it should cause any issue.

Thanks

**Comment by THEETB** [comment]
Hi @bwalderman 

 Thanks for following up. I am currently using webdriver manager in script to manage the webdriver but i am running into this issue all the time. I am trying to find solution to easily manage webdriver or to find a approach which can eliminate webdriver dependency.

**Comment by GCuser99** [comment]
Thanks @bwalderman - upon further research I found your suggested solution here: [issue 39](https://github.com/MicrosoftEdge/EdgeWebDriver/issues/39#issuecomment-1182478500)

**Comment by bwalderman** [comment]
> Hi @bwalderman
> 
> Thanks for following up. I am currently using webdriver manager in script to manage the webdriver but i am running into this issue all the time. I am trying to find solution to easily manage webdriver or to find a approach which can eliminate webdriver dependency.

@THEETB can you share more details or sample code about the webdriver manager script you are using?

**Comment by bwalderman** [comment]
Closing since there hasn't been any follow up.
