### ISSUE TITLE
Unable to handle windows with the latest versions of IE driver and selenium java versions

### ISSUE THREAD

**Issue by bwalderman** [MicrosoftEdge/EdgeWebDriver#59]
Unable to handle windows with the latest versions of IE driver and selenium java versions.Any one was able to find a solution or workaround for the same.Can we please reopen this issue.

Testing my application on edge with ie compatibility. 

Test Steps:
1.Launching appliaction edge with ie mode (Edge version 107*. IE 11 ,tested with selenium  java 4.0-4.5,IE driver version tested with 4.1-4.6)
2.Entering username and password and clicking on Submit. Clicking closes this window and launches a new window and a subwindow.
  Trying to get window.handles at this point the test fails with exception no window or window is already  closed 

The above scenario works with IE.

Application works fine in IE

_Originally posted by @jyosha3 in https://github.com/MicrosoftEdge/EdgeWebDriver/issues/19#issuecomment-1325491296_

**Comment by bwalderman** [comment]
@jyosha3 can you provide a minimal test page that reproduces the issue?

**Comment by jyosha3** [comment]
I will try to find a similar  web page and share it with you.
