### ISSUE TITLE
Can't run Selenium side runner for Edge with a current profile

### ISSUE THREAD

**Issue by rdomingo11** [MicrosoftEdge/EdgeWebDriver#60]
Even though the edge can be spawned, it couldn't inherit the current profile. In fact, the browser doesn't use the logged in profile.

Btw, this is the command that I've been running.
selenium-side-runner -c "user-data-dir='C:\Users\\AppData\Local\Microsoft\Edge\User Data\' profile-directory=Default browserName=MicrosoftEdge" -s "http:\127.0.0.1:9515" -d *.side

Is the configuration incorrect?

**Comment by bwalderman** [comment]
Hi @rdomingo11. I'm not very familiar with selenium-side-runner, but from looking at the docs at https://www.npmjs.com/package/selenium-side-runner I think the command you are using isn't quite correct.

Edge (or Chrome) command line args need to be passed as edgeOptions (or chromeOptions), e.g.:

```
selenium-side-runner -c "ms:edgeOptions.args=[disable-infobars, headless]"
```

Try the following:

```
selenium-side-runner -c "ms:edgeOptions.args=['user-data-dir=C:\Users\AppData\Local\Microsoft\Edge\User Data', 'profile-directory=Default']" browserName=MicrosoftEdge" -s "http:\127.0.0.1:9515" -d *.side
```

I don't have Selenium IDE or a .side file handy so I can't test this myself. You may need to adjust the quotes slightly if the above doesn't work. Hope this helps.

**Comment by rdomingo11** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/9833439/207693945-1939b1c7-3c4a-410b-953d-7adcb97a67c6.png">
Hi, it didn't work. It is still using the temporary profile that the selenium-side-runner has generated.

**Comment by bwalderman** [comment]
From the screenshot, it looks like the single quotes are being included in the final command line seen by Edge, which won't work. Try removing the single quotes around each argument:

```
selenium-side-runner -c "ms:edgeOptions.args=[user-data-dir=C:\Users\AppData\Local\Microsoft\Edge\User Data, profile-directory=Default]" browserName=MicrosoftEdge" -s "http:\127.0.0.1:9515" -d *.side
```

If that doesn't work, I'd recommend contacting the Selenium developers for guidance about how to properly pass args to selenium-side-runner.

**Comment by bwalderman** [comment]
Closing. This seems to be an external issue with command line parsing in selenium-side-runner.
