### ISSUE TITLE
Edge IE mode inprivate browsing

### ISSUE THREAD

**Issue by edochsibur** [MicrosoftEdge/EdgeWebDriver#63]
Hi,

It is not possible to set "inprivate" browsing when running Edge in IE mode. 
The capability only exist for EdgeOptions with chromium to addArguments not for InternetExplorerOptions driver.

Can you let me know if it is possible to set this and if available how to configure this?

Thanks

**Comment by bwalderman** [comment]
Hi @dorianlupu. It isn't possible to set Edge to inprivate mode when running with IEDriver. The latest version of IEDriver does use a temporary user data directory by default though, so your test will run with an isolated user profile.
