### ISSUE TITLE
Web Driver Download

### ISSUE THREAD

**Issue by john-technegol** [MicrosoftEdge/EdgeWebDriver#64]
Apologies, I know this is probably the wrong place to post. The download site https://developer.microsoft.com/microsoft-edge/tools/webdriver/ is not currently working.

I can't see where to contact to notify someone.

Thanks

John

**Comment by rbaudouinn** [comment]
I have the same problem. The site
https://developer.microsoft.com/es-es/microsoft-edge/tools/webdriver/ is not working.

Please your help

Thanks
Renato B

**Comment by bwalderman** [comment]
The site was down briefly but is up and running again. Feel free to report outages here. Our team can contact the site maintainers.
