### ISSUE TITLE
Remote connection to edge webdriver

### ISSUE THREAD

**Issue by parkhomchukp** [MicrosoftEdge/EdgeWebDriver#67]
I used to write tests for html based Edge browser using selenium and Microsoft WebDriver. In legacy Microsoft WebDriver there was a possibility to connect to the driver remotely.
In Python code it looked like:
```
from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
from msedge.selenium_tools import EdgeOptions

options = EdgeOptions()
driver = RemoteWebDriver(command_executor="http://host:port", options=options)
driver.get("https://microsoft.com")
driver.quit()
```

Unless, when I run new Microsoft Edge browser - I see message like "Only local connections are allowed".

The question is: "Is there a possibility to run tests remotely using Edge WebDriver"?

**Comment by bwalderman** [comment]
Please uninstall msedge.selenium_tools and upgrade to Selenium 4 if possible. msedge.selenium_tools was a temporary workaround for adding Edge Chromium support to Selenium 3 and is no longer supported. You can read more about upgrading here: https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp#upgrading-from-selenium-3

Like ChromeDriver, MSEdgeDriver only supports localhost connections by default. You can start msedgedriver with the `--allowed-ips=LIST` command line arg to provide a list of remote IP addresses that are allowed to connect. Run `msedgedriver --help` for more info.

If you don't know the IP address that need to be allowed ahead of time, or would like to allow all remote connections from any IP, you can provide an empty list like so:

`msedgedriver --allowed-ips=`
