### ISSUE TITLE
Microsoft EdgeBrowser is not working through selenium

### ISSUE THREAD

**Issue by LokeshTippalurie** [MicrosoftEdge/EdgeWebDriver#68]
Hi Team,

We are trying to launch Microsoft EdgeBrowser using selenium.
EdgeBrowser version is 108.0.1462.76.
selenium version is 4.7.2

Getting below Exception.

Starting Microsoft Edge WebDriver 108.0.1462.76 (5feb330873638e9bb5dfe2a398aadcb50a36c860) on port 60804
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'A356O0L58CW29E7', ip: '192.168.43.186', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)

**Comment by bwalderman** [comment]
@LokeshTippalurie can you share the Selenium code you are using to launch Edge, including any special EdgeOptions?
