### ISSUE TITLE
[Feature] Can this support Edge Profile login? 

### ISSUE THREAD

**Issue by zeuscai** [MicrosoftEdge/EdgeWebDriver#7]
Does or will EdgeWebDriver support pre-setting Edge Profile? Or anyway can automatically testing any scenarios requires user profile login?

**Comment by bwalderman** [comment]
You can use command line arguments to configure Edge to launch with an existing user data directory and profile. For example:

```csharp
var options = new EdgeOptions();
options.AddArgument("--user-data-dir=\"C:\Users\<your user name>\AppData\Local\Microsoft\Edge\User Data\"");
```

When a `--user-data-dir` is configured this way, Edge WebDriver will launch Edge with that user data directory instead of creating a temporary one.
