### ISSUE TITLE
Need edge driver version 98

### ISSUE THREAD

**Issue by SowmiyaGovindharaj** [MicrosoftEdge/EdgeWebDriver#70]
I did not find the edge driver version below 99. I need this driver since our electron application which support only the driver versions below 99.

**Comment by bwalderman** [comment]
Electron is based on Chromium, not Edge. You will need to use ChromeDriver. Here's some information on locating the correct version: https://chromedriver.chromium.org/downloads/version-selection

This might also be helpful: https://www.electronjs.org/docs/latest/tutorial/using-selenium-and-webdriver
