### ISSUE TITLE
When opening the edge(111.0.1661.44 version) browser in selenium headless mode, the actual opening is a chrome browser

### ISSUE THREAD

**Issue by yaohongfenglove** [MicrosoftEdge/EdgeWebDriver#74]
In the 111.0.1661.44 version of Edge, when headless mode is enabled, the actual browser opened is Chrome instead of Edge. For example, the following image(In headless mode, use driver.get_screenshot_as_file to take) shows an edge in headless mode with bind.com chat mode open. Obviously, the enabled browser is not edge, but Chrome.
![image](https://user-images.githubusercontent.com/71106576/226303526-d41d276c-f9eb-4c66-915d-ff5aa6cefc37.png)

**Comment by guangyuexu** [comment]
Thanks for reporting the issue. I cannot reproduce this issue in Edge 111 and later versions. Here are my repro steps:
1. open edge 111 in headless mode with command `msedge.exe --headless --remote-debugging-port=9222 --user-data-dir=c:\temp\edge https:/www.bing.com` (instance 1)
2. open another edge browser and goto edge://inspect (instance 2)
3. inspect the page in instance 1
4. click the chat button on the top of the page
![image](https://user-images.githubusercontent.com/64437609/230231677-4cbb3b3f-1352-4b53-873f-9de4c8f422c1.png)
5. a new page with "start chatting" button will show up as follows
![image](https://user-images.githubusercontent.com/64437609/230231655-939421da-84b8-48cf-8750-7d6ada6a342c.png)

Would you please provide more details about how to repro the issue?

**Comment by yaohongfenglove** [comment]
Thank you for taking the time to answer my question. 
I am now providing an attachment to reproduce this issue in Edge 111.0.1661.62 version. **(Probabilistic bug reproduced , I ran it three times and both of the last two times reproduced)**

Here are my repro steps:
1. run "python.exe headless_edge_issue.py"
2. two png images will be generated in the directory, one in headless mode and the other in non headless mode

```
# headless_edge_issue.py

import time

from selenium import webdriver
from selenium.webdriver.edge.options import Options


def screenshot_to_png(link, headless):

    edge_options = Options()

    if headless:
        edge_options.add_argument('--headless')

    edge_options.add_argument('--disable-gpu')
    edge_options.add_argument('--no-sandbox')
    edge_options.add_argument("--start-maximized")

    driver = webdriver.Edge(options=edge_options, executable_path='./msedgedriver.exe')
    driver.implicitly_wait(30)

    try:
        driver.get(link)
        time.sleep(10)

        driver.save_screenshot('./screenshot_with_headless_is_{}.png'.format(headless))
 
    finally:
        driver.quit()


if __name__ == '__main__':
    screenshot_to_png(link="https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx", headless=True)
    screenshot_to_png(link="https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx", headless=False)
   
```

The two images are as follows, It is obvious that the browser opened in headless mode is not an edge browser

![screenshot_with_headless_is_True](https://user-images.githubusercontent.com/71106576/230293895-2737817b-0143-44e8-93dd-625967ff1bd4.png)

![screenshot_with_headless_is_False](https://user-images.githubusercontent.com/71106576/230293910-f5f8da83-8b3c-40ac-abe4-bc9db21afd0b.png)

![edge_version](https://user-images.githubusercontent.com/71106576/230293151-f9f548c6-8d28-4c03-9722-522af06621e5.png)

[edgedriver_win64.zip](https://github.com/MicrosoftEdge/EdgeWebDriver/files/11167132/edgedriver_win64.zip)

**Comment by bwalderman** [comment]
@yaohongfenglove , you might be interested in launching with the `--headless=new` command line arg (instead of `--headless`). It was recently introduced in Chrome and is available in Edge too. The old headless mode is a separate Chromium-based browser embedded in the main browser and can cause pages to behave differently. The new headless mode uses the real browser and should be recognized as Edge.

More details about the new headless mode: https://developer.chrome.com/articles/new-headless/

**Comment by yaohongfenglove** [comment]
Thank you. The document(https://developer.chrome.com/articles/new-headless/) you provided perfectly solved my problem, I just need to change -- headless to -- headless=new. 

```
# headless_edge_issue.py

import time

from selenium import webdriver
from selenium.webdriver.edge.options import Options


def screenshot_to_png(link, headless):

    edge_options = Options()

    if headless:
        edge_options.add_argument('--headless=new')

    edge_options.add_argument('--disable-gpu')
    edge_options.add_argument('--no-sandbox')
    edge_options.add_argument("--start-maximized")

    driver = webdriver.Edge(options=edge_options, executable_path='./msedgedriver.exe')
    driver.implicitly_wait(30)

    try:
        driver.get(link)
        time.sleep(10)

        driver.save_screenshot('./screenshot_with_headless_is_{}.png'.format(headless))
 
    finally:
        driver.quit()


if __name__ == '__main__':
    screenshot_to_png(link="https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx", headless=True)
    screenshot_to_png(link="https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx", headless=False)
```
