### ISSUE TITLE
disable-build-check no longer working starting Edgedriver 111

### ISSUE THREAD

**Issue by mmchen01** [MicrosoftEdge/EdgeWebDriver#76]
I typically run the latest stable edgedriver version with Edge dev and beta with the disable-build-check flag that allows me to bypass version matching, however starting Edgedriver 111 the disable-build-check flag no longer works and I cannot use this flag to run Edgedriver 111 with non-matcing Edge versions.

**Comment by bwalderman** [comment]
Hi @mmchen01, we don't support using the `--disable-build-check` for bypassing the version check. This may have happened to work in the past, but the only supported way to test a version of Edge is to use the matching driver. Assuming you are using Selenium, they have made the process of installing the correct driver a lot easier with Selenium Manager. You can find out more about it here: https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#1-selenium-manager-beta
