### ISSUE TITLE
Selenium compatibility Edge control

### ISSUE THREAD

**Issue by avdhut18** [MicrosoftEdge/EdgeWebDriver#78]
We tried selenium 4. We need a way to connect our WPF application (Edge controls) with our selenium scripts. 

Remote debugging port to connect to WebView2 instance is randomly getting change in our application, we are looking for solution how to add fix debugging port in our WPF application and run our selenium test cases on webview2 application

We were able to do the same for chrome controls with --remote-debugging-port=xxxx. The idea is to attach remote debugging port inside WPF application during runtime. 

However, for Edge controls we are not sure how to use --remote-debugging-port=xxxx to attach remote debugging port inside WPF application 

We can explain this better on call
please suggest

**Comment by bwalderman** [comment]
Hi @avdhut18, I've asked the WebView2 team for advice on setting command line args for a WPF-based WebView2 control. I'm not sure if this is the best method, but you can try setting the `ADDITIONAL_BROWSER_ARGUMENTS` environment variable, which allows you to pass arguments through to the WebView2 process:

```csharp
Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--remote-debugging-port=9222");
```

**Comment by bwalderman** [comment]
@avdhut18 using the environment variable above will be the best way to enable remote debugging and WebDriver for the WebView2 control.

Here's some more info:

https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver#approach-2-attaching-microsoft-edge-webdriver-to-a-running-webview2-app

https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel#using-an-environment-variable
