### ISSUE TITLE
Edge in IE mode unable to execute when executed with Administrator mode

### ISSUE THREAD

**Issue by kalpeshdlad** [MicrosoftEdge/EdgeWebDriver#79]
https://github.com/SeleniumHQ/selenium/issues/11848

I am trying to execute one test on Edge with IE mode.
I have attached my code which will launch Edge in IE mode with different parameters.

When I execute this python file from command prompt opened as normal user then it works fine.
But If I execute same code with same configuration from command prompt opened with elevated access (run as administrator) then control is never returned and I do not get log "after launch".

PID indicated in driver log was not in seen TaskManager as well.

I need to execute this as Administrator only.

    from selenium import webdriver

    def Open_Edge_in_IEMOde(profile_dir, download_dir, driverpath):

    ieOptions = webdriver.ie.webdriver.Options()
    ieOptions.add_argument("user-data-dir=" + profile_dir)
    ieOptions.add_argument("profile-directory=Default")
    ieOptions.add_argument("browser_attach_timeout=5000")

    ieOptions.use_chromium = True
    ieOptions.add_additional_option("ignoreProtectedModeSettings", True)
    ieOptions.add_additional_option("initialBrowserUrl", "https://www.wikipedia.org/")
    ieOptions.add_additional_option("ie.edgechromium", True)

    ieOptions.add_additional_option("ie.edgepath", 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe')
    print("before launch")
    driver = webdriver.Ie(executable_path=driverpath, options=ieOptions, log_level="TRACE", log_file=r"W:\\logfile_bot.log")
    print("after launch")
    driver.get("https://www.google.com/")
`

**Comment by bwalderman** [comment]
Hi @kalpeshdlad, Edge will not launch in adminstrator mode. This is explicitly not supported for security reasons. The test will need to run unelevated for Edge to launch successfully.
