### ISSUE TITLE
Could not start new session. Possible causes are invalid address of the remote server or browser start-up failure.

### ISSUE THREAD

**Issue by primejay24** [MicrosoftEdge/EdgeWebDriver#83]
Microsoft edge documentey Provided edge in ie mode code but not working so have get another selenium code but facing issues.it works fine untill RDP session active but once session inactive get above mentioned error .

Below code is used ,
System.setProperty("webdriver.ie.driver", "IE Driver Path"); InternetExplorerOptions ieOptions = new InternetExplorerOptions();

ieOptions.attachToEdgeChrome ();

ieOptions.ignore ZoomSettings ();

ieOptions.withEdgeExecutable Path ("C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe");

driver = new InternetExplorerDriver (ieOptions);

driver.manage().deleteAllCookies();

driver.manage () .window () .maximize();

driver.get("https://www.finacle.com");

If any alternative solutions to resolve this problem please share .

**Comment by bwalderman** [comment]
This is a known issue: #15 

As a workaround, you will need to ensure the RDP session remains active while running IE Mode tests.
