### ISSUE TITLE
Unable to use sendkeys() for password in Edge using Selenium Automation

### ISSUE THREAD

**Issue by suryak82** [MicrosoftEdge/EdgeWebDriver#84]
I am using IntelliJ writing tests of selenium automation., I am trying to signin into an application, I can use the sendkeys() method successfully to enter the username but when trying to enter the password, it repeatedly failed. Please look into this.

**Comment by bwalderman** [comment]
Does the same problem occur when using Chrome with ChromeDriver?

**Comment by Ramuvelpula96** [comment]
public class EncryptDecryptUtil {
	
	//shall be changed with more complex crypto key
	private static String mpCryptoPassword = "#BorNT0L!ve@ndFi4ht";

	private EncryptDecryptUtil() {
		
	}
	
    public static String encrypt(String password) {
    	StandardPBEStringEncryptor encryptor = new StandardPBEStringEncryptor();
   		encryptor.setPassword(mpCryptoPassword);
   		return encryptor.encrypt(password);
    }
    
    public static String decrypt(String encryptedPassword) {
    	
        StandardPBEStringEncryptor decryptor = new StandardPBEStringEncryptor();
        decryptor.setPassword(mpCryptoPassword);
        return decryptor.decrypt(encryptedPassword);
    }
 use this line of code for the password    ---EncryptDecryptUtil.decrypt(this.testData.getClBusinessDetails().getPassWord()));

**Comment by bwalderman** [comment]
Closing as not able to repro.
