### ISSUE TITLE
Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: crashed. Running script using jenkins.

### ISSUE THREAD

**Issue by Shrinivas-pednekar** [MicrosoftEdge/EdgeWebDriver#85]
Getting "Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: crashed." this error when I execute selenium script using Jenkins job. But same script running successfully from eclipce IDE.
Edge browser version - 113.0.1774.42
Wed driver manager version - 5.3.3

Find below error:

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
edge
Starting Microsoft Edge WebDriver 113.0.1774.42 (881f341807652d12d315d777648a97d88e1ff425) on port 4712
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
[ERROR] Tests run: 15, Failures: 2, Errors: 0, Skipped: 13, Time elapsed: 5.065 s <<< FAILURE! - in TestSuite
[ERROR] initialize(portfolio_test.user.TC01_UserLoginTest) Time elapsed: 3.818 s <<< FAILURE!
org.openqa.selenium.SessionNotCreatedException:
Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: crashed.
(unknown error: DevToolsActivePort file doesn't exist)
(The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.2.1'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [--remote-allow-origins=*], extensions: []}}]}]

**Comment by bwalderman** [comment]
Can you share more info about how Jenkins is set up? Is it running as a Windows service? If so, Edge won't be able to start successfully. Edge WebDriver and Edge need to run as a normal interactive user on Windows. Services run in a special session as the "SYSTEM" user which is not supported.

**Comment by Shrinivas-pednekar** [comment]
Thanks for your response on above issue.
Running Jenkins as a standalone application resolved my issue.  Now my script able to launch the edge browser. 
Can we except in the future jenkins windows service supported to edge browser as well?

**Comment by bwalderman** [comment]
> Can we except in the future jenkins windows service supported to edge browser as well?

Sorry, for security reasons, we don't support running Edge as administrator, or in the context of a Windows service. The best options are to either run Jenkins as a standalone application, or run msedgedriver.exe standalone using a known port and configure your Jenkins script to connect to it. Hope this helps.

**Comment by Shrinivas-pednekar** [comment]
Yes. Its helps. Thank you for your response.
