### ISSUE TITLE
edgeoptions class does not have addExtensions method 

### ISSUE THREAD

**Issue by bkckrao** [MicrosoftEdge/EdgeWebDriver#90]
edgeOptions class does not have addExtensions method 

Dear Team,

we are using selenium-java 3.141.59 version and observed that edgeoptions class does not have addExtensions or install extension method. Is there any alternate way to add extensions?

**Comment by bwalderman** [comment]
Hi @bkckrao . Please update to Selenium 4. The EdgeOptions class in Selenium 4 has addExtensions and all of the other options supported by Chromium-based browsers. Selenium 3.141.59 is out of support.
