### ISSUE TITLE
 Getting blank or black screenshot while running the test scripts on azure self hosted agent in service mode for Edge in IE mode

### ISSUE THREAD

**Issue by AbhiAuto** [MicrosoftEdge/EdgeWebDriver#92]
We gets a blank or black screenshot while running test automation scripts on Azure Self Hosted agents (Windows 2019 server 64 Bit) in service mode on Edge in IE mode. The execution is flawless, with no errors.

Note : While working on the local machine on Windows 10 for debugging and development, as well as in the interactive mode on Windows 2019 64 bit, the screenshot does not seem blank or black.

![image](https://github.com/MicrosoftEdge/EdgeWebDriver/assets/26138640/4d847430-b708-4c13-ad7b-6c4231887876)

We have raised the defect under Selenium support and we received below the response. Issue details( https://github.com/SeleniumHQ/selenium/issues/12247 ) 

![image](https://github.com/MicrosoftEdge/EdgeWebDriver/assets/26138640/bd1ee9bd-615c-428f-af52-6e3901dba844)

Run the sample test scripts on Azure Self Hosted agents (Windows 2019 server 64 bit) in service mode on Edge in IE mode and capture a snapshot with the code below. We will afterwards attach the screenshot to the Extent Report(5.0.9) as media.

Code : 

public Media takeScreenshot() {
Media media = null;
try {
TakesScreenshot scrShot = ((TakesScreenshot) BrowserDriver.getDriver());
String screenBase = scrShot.getScreenshotAs(OutputType.BASE64);
media = MediaEntityBuilder.createScreenCaptureFromBase64String(screenBase).build();	
} catch (Exception e) {
e.printStackTrace();
}
return media;
}

**Comment by bwalderman** [comment]
Running IE Driver as a service is expressly unsupported by the Selenium maintainers: https://www.selenium.dev/documentation/ie_driver_server/#running-iedriverserverexe-under-a-windows-service

Here's some useful guidance on configuring a self-hosted Azure agent to run tests that require visible UI:
https://learn.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest#visible-ui-mode

**Comment by bwalderman** [comment]
Closing since there hasn't been any activity. Feel free to reopen if there are any further questions after reviewing the docs above.
