### ISSUE TITLE
How can I allow mic/camera and block notifications permissions using EdgeOptions? Selenium 1.141

### ISSUE THREAD

**Issue by shubhamdumbare** [MicrosoftEdge/EdgeWebDriver#98]

**Comment by shubhamdumbare** [comment]
No more reproducible

**Comment by bwalderman** [comment]
Edge WebDriver and ChromeDriver both support the standard W3C WebDriver [Set Permission](https://w3c.github.io/permissions/#set-permission-command) command. Please check the docs for the version of Selenium you are using to see how to call this command.
